### ISSUE TITLE
NXxpcs: what's the difference between the "entry_identifier" and the "scan_number"? What purpose are they trying to fulfill?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1004]
what's the difference between the "entry_identifier" and the "scan_number"? What purpose are they trying to fulfill?

https://github.com/nexusformat/definitions/blob/151a36dc15b4995ebd22b69425474564c7df2594/contributed_definitions/NXxpcs.nxdl.xml#L58-L62

https://github.com/nexusformat/definitions/blob/151a36dc15b4995ebd22b69425474564c7df2594/contributed_definitions/NXxpcs.nxdl.xml#L68-L74

_Originally posted by @benajamin in https://github.com/nexusformat/definitions/pull/982#discussion_r819091781_

**Comment by prjemian** [comment]
@ambarb @AbbyGI @JulReinhardt - can you comment?

**Comment by prjemian** [comment]
No one else has commented, I'll respond.

Both of these terms arise from the data acquisition system. 

- `scan_number`: A positive integer which is incremented (or reset, usually to 1) for each new measurement.  Not guaranteed to be unique.
- `entry_identifier`: A unique text code ([UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) is typical) to identify this data in a database.  In Python, such a text code is generated with [`uuid.uuid4()`](https://docs.python.org/3.9/library/uuid.html#uuid.uuid4)

**Comment by prjemian** [comment]
Ah, the UUID is another field:

https://github.com/nexusformat/definitions/blob/151a36dc15b4995ebd22b69425474564c7df2594/contributed_definitions/NXxpcs.nxdl.xml#L63-L67

**Comment by benajamin** [comment]
Maybe we should propose deprecating `entry_identifier` and see who complains and then let them give an answer?

**Comment by prjemian** [comment]
Still waiting for response from XPCS community.  @ambarb?

**Comment by prjemian** [comment]
Moving to next milestone.

**Comment by ambarb** [comment]
### entry_identifier
```
Unique identifier for the experiment. 
```

historically, with spec collection, this isn't actually unique any more. 
proposal to NeXUS to be "Locally unique identifier" in case people are using spec or equivalent and not bluesky or neutron collection.  Change locally to the below and also submit to NeXus community at large.

```
**Locally** unique identifier for the experiment **/ run / scan.** 

For spec users, this is the `SCAN_N` (the scan number) . For bluesky users, this is the header["scan_id"].
```
because this may be used by spec-based collection to keep track of data, and has evolved over the last 14 years.



### scan_number
```
     Scan number (must be an integer). 
  
     NOTE: Link to collection_identifier. 
```

Belongs to NXxpcs only.  This is for bluesky-like data collection and would be run `"scan_id"` so users and developers can choose either method (uid or scan_id) to retrieve data.   If using spec-like, this would be redundant.  
**We will mark this field (`scan_number`) for deletion**


### entry_identifier_uuid: (optional) 
```
(optional) UUID identifier for this entry.
```
this seems to be only used by NXxpcs but it also now in NXentry so it requires an at-large discussion.  However, if we delete scan_number, we need to make clear to all bluesky users/developers what to do because NX definitions associated with bluesky collection need to have `uid` and `scan_id` to satisfy human and computer needs.

UUID means something specific and would be a clue to those that know what it means.

proposed changes:
### entry_identifier_uuid: (optional) 
```
(optional) UUID identifier for this entry. See [standard](https://www.rfc-editor.org/rfc/rfc4122.html) or [wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier)

For bluesky users, this is the run `"uid"` and is expected for that application. Typically, spec users will not use this field without further engineering.
```

**Comment by prjemian** [comment]
I'll make these change in a new branch and PR.

**Comment by prjemian** [comment]
@tacaswell: In https://github.com/nexusformat/definitions/issues/1004#issuecomment-1242213372 (above), there is the suggestion that the general definition of `entry_identifier` is confusing in its use of the word *unique*.  This would be a good first issue for you to open in the NeXus definitions repository.
