### ISSUE TITLE
Extend HTML documentation of base classes for overrides

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1057]
[HTML documentation pages](https://github.com/nexusformat/NIAC/issues/107) always reference nicely the base class of each group in a definition file, but it references only the most basic base class! Eg. NXarpes/instrument/source/ references NXsource, but not NXinstrument/NXsource (which may have already extended/overridden NXsource)

**Comment by PeterC-DLS** [comment]
Do you meant reference, eg. NXsource, within the application definition?

**Comment by prjemian** [comment]
@PeterC-DLS Will this issue be resolved in the next days?  Is it necessary to resolve this for release of NXDL now?

**Comment by PeterC-DLS** [comment]
Not sure if I have time to do this before release, so I'm happy to postpone it.

**Comment by sanbrock** [comment]
A solution to this problem is to add a direct link to the vocabulary item referenced first. E.g.:  NXXkappa/ENTRY/definition
 definition: (required) [NX_CHAR](https://github.com/orgs/nexusformat/projects/nxdl-types.html#nx-char) [<NXxbase/…/definition>](https://github.com/orgs/nexusformat/projects/3/views/NXxbase.html#nxxbase-entry-definition-field)  
This is implemented in the PR #1272

**Comment by sanbrock** [comment]
Similarly, for `NXxkappa/entry` we should indicate that although its base class type is `NXentry`,  it is actually extending `NXxbase/entry`, which is already an extended `NXentry`.  We should provide this information by linking the first reference, and not only the very base reference. Hence, it should look like:
entry: (required) [NXentry](https://github.com/orgs/nexusformat/projects/3/base_classes/NXentry.html#nxentry) [<NXxbase/entry>](https://github.com/orgs/nexusformat/projects/3/views/NXxbase.html#nxxbase-entry-group)
