### ISSUE TITLE
What does a NXbeam group defined inside NXinstrument means? 

### ISSUE THREAD

**Issue by Gigarrum** [nexusformat/definitions#1263]
According to [NXbeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html) documentation the information inside the group refers to "properties of the neutron or X-ray beam at a given location" and that the group "is intented to be referenced by beamline component groups within the [NXinstrument](https://manual.nexusformat.org/classes/base_classes/NXinstrument.html#nxinstrument)". 

Considering that, I understand that a [NXbeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html) group should be defined inside groups that define specific instrumentation (e.g: [NXdetector](https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector), ) or that defines the sample ([NXsample](https://manual.nexusformat.org/classes/base_classes/NXsample.html?highlight=nxsample)) defined in the documentation inside the [NXsample](https://manual.nexusformat.org/classes/base_classes/NXsample.html?highlight=nxsample), so it is possible to correctly know the position of the beam being defined. 

However on [NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html) application definition the [NXbeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html)  group is defined directly inside the [NXinstrument](https://manual.nexusformat.org/classes/base_classes/NXinstrument.html#nxinstrument) group, that means it is being considered the same beam configuration over all devices? If yes, I would recommend adding this interpretation to docs on [NXbeam](https://manual.nexusformat.org/classes/base_classes/NXbeam.html) otherwise [NXmx]([NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html)) application definition may need corrections.

**Comment by phyy-nx** [comment]
From Code Camp discussion:

- If the NXbeam is in NXinstrument and not NXsample, at least for NXmx, it's because there is the beam is a component that is part of the instrument.
- Contrariwise, the beam could be different as it moves through the instrument, and when NXbeam is in NXsample that's the state of the beam at the sample

Generally it's a matter for the individual application definitions and the communities that manage them.

@Gigarrum, if you would like further clarification to be incorporated into NXbeam, could you write the words you are thinking into a pull request that would close this issue?  Otherwise, I'd say go ahead and close it if you are satisfied.  Thanks for the questions!

**Comment by Gigarrum** [comment]
@phyy-nx can you change the status of this issue to "Ready for Review", I don't have permissions to do so.

**Comment by phyy-nx** [comment]
Done, and I've added #1283 to the project
