### ISSUE TITLE
complex units, like eV/mm

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1435]
- [ ] Neither NX_ENERGY nor NX_PER_LENGTH is the correct choice for eV/mm as monochromator disperion is reported at FLASH
- [ ] NeXus doc states ["However, any field must have a units attribute which describes the units."](https://manual.nexusformat.org/datarules.html#index-26) but hardly anybody does this via adding an attribute named  "units" to **all** fields, i.e. also fields NX_CHAR must have a units attribute, feels that this is too tight of being a useful constraint.
- [ ] #1487

**Comment by prjemian** [comment]
Is appropriate to define a new type of units for this purpose?  Here is where they are defined.
https://github.com/nexusformat/definitions/blob/main/nxdlTypes.xsd

**Comment by phyy-nx** [comment]
Proposal:

Allow the attribute, `units`, to in addition to being `NX_ANGLE`, `NX_AREA`, etc, be a vector of fractional SI dimensions.  Example, 

```
<field name="mega_unit" type="NX_FLOAT" units="0,1,2,3,4,0,0">
```

This means the user needs to include the attribute `units`, and the string they provide needs to have dimensionality of `mass * time^2 * electric current^3 * temperature^4`

The vector is:
length
mass
time
electric current
thermodynamic temperature
amount of substance
luminous intensity

This is the same order as in UDunits (link)

The HTML rendering won't show the numbers, but instead will use the SI defaults and the exponents to be more human readable.  The XML will have the vector.

(the NIAC will return to this tomorrow)

**Comment by tacaswell** [comment]
```
' '.join(__ for __ in (f'{_}^{v}' if v != 0 else '' for _, v in zip(('s', 'm', 'kg', 'A', 'K', 'mol', 'cd'), (1, 0, 0, 3, -1, 0))) if __)

```

**Comment by prjemian** [comment]
A sequence of seven numbers (in the NXDL file) is hard to embrace as a person who is coaching people to write new application definitions.  This is a code that must be remembered.  I foresee continual challenges about the proper order of the numbers, for example.  

Perhaps there is another, more natural, way to implement this idea?

The problem to be solve here is that a defined a list of defined units categories might not be bounded.  To allow the NeXus standard to be flexible to our community, we need a more robust system to describe expected units as our community's needs expand.

We could add a `unit_example="ev/mm"` attribute for the monochromator disperion cited above.  In general, the `unit_example` would have a human readable expression that is convertible with UDunits, pint, whatever.  This type of expression satisfies the list of numbers with a human readable text.  The expression is comparable to the examples already provided in `nxdlTypes.xsd`.  Could it eventually replace the unit categories altogether?

**Comment by prjemian** [comment]
The second example above (`units="0,1,2,3,4,0,0"`) could be expressed
 `unit_example="g * s^2 * A^3 * K^4"`.  It could also be expressed in other variations which evaluate to the same units.

**Comment by tacaswell** [comment]
```python
n [24]: {**dict.fromkeys(('s', 'm', 'kg', 'A', 'K', 'mol', 'cd'), 0), **{k:int(v) for k, v in (g.split('^') for g in 's^1 A^3 K^-1'.split())}}
Out[24]: {'s': 1, 'm': 0, 'kg': 0, 'A': 3, 'K': -1, 'mol': 0, 'cd': 0}
```

is also pretty straight forward (modulo details like supporting `^1` implicitly).

Maybe instead of trying to write a "nice" string we have to parse, we instead make it a json object as: 


```xml
<field name="mega_unit" type="NX_FLOAT" units="{'s': 1, 'm': 0, 'kg': 0, 'A': 3, 'K': -1, 'mol': 0, 'cd': 0}">
```

It is a bit verbose, but it is unambiguous to both humans and computers.  Dropping the keys who's value is 0 is likely reasonable.

**Comment by phyy-nx** [comment]
Of these I prefer the vector representation, but only because the user would never see it.  The HTML for the documentation would be rendered as `g * s^2 * A^3 * K^4`, and we would recommend that developers put in their doc strings the more conventional name for their units. Only the XML would contain the more machine-readable vector.

The `unit_example` attribute is worth considering though.

**Comment by phyy-nx** [comment]
Note this is literally #1325, with the addition of extra HTML rendering code to smooth out the non-human readable unit vector.

**Comment by phyy-nx** [comment]
Alternate proposal:

- If a unit is not provided by the list of NeXus unit categories, instead of providing a category, the field statement can include an example of the units directly.
- The example does not constrain the scale of the units. For example, if the unit is `eV/mm`, they user could specify in a data file `eV/cm`, or any other unit that is convertible to the example given.

Example:

`<field name="monochromator_dispersion" units="eV/mm">`

It is recommended that users and application developers check if their units and their unit examples adhere to the [UDUNITS](https://www.unidata.ucar.edu/software/udunits/) standard.

This proposal is accepted by NIAC vote as part of [NIAC2024](https://www.nexusformat.org/NIAC2024.html)

**Comment by prjemian** [comment]
Related issues include

- #918 
- #1325

**Comment by prjemian** [comment]
Probably needs a modification to the NXDL Schema.
