### ISSUE TITLE
license dates

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/definitions#1437]
Should not we use consistent license dates for all nxdl.xml files? Specifically 2008-2024 throughout

**Comment by prjemian** [comment]
There are reasons why a copyright starting date may differ.  Is this a problem?  

I don't believe we should go and change this type of history.

**Comment by mkuehbach** [comment]
Poten 
https://reuse.software/

**Comment by phyy-nx** [comment]
Discussion from NIAC: it's likely the different copyright statements arose either from the time in which the given file was created, or a copypaste from one file to another.  The question is a) is it appropriate to have the copyright in each individual file at all, and b) if so, should they all be the same?  

@tacaswell a) if all the files are part of the same work doesn't matter, but if they are separate works they do matter b) yes

Proposal, make all the copyright statements the same, and set the ranges to `2008-`

**Comment by paulmillar** [comment]
The usual IANAL disclaimer applies, but I believe copyright year indicates when changes were made (and published).

The procedure (as I understand it) is that, each time a file is edited, the copyright date-range should be updated to include the current year.  If the date already shows the current year then no change is needed.

For example, if a file states it is "copyright 2000--2023" then the first edit of 2024 should updated the copyright year to "2000--2024".  Subsequent changes in 2024 would leave the date unchanged.

From [this answer](https://www.quora.com/Do-you-have-to-add-a-year-for-copyright), the answer's author claims that intermittent (non-continuous) edits should be written as comma-separated list of date-ranges (where a date-range could be a single year). For example, a file created in 2020 and updated in 2024 should be written "copyright 2020,2024" and not "copyright 2020--2024".

To be honest, I've never seen copyright asserted using anything other than a single date-range ("2020--2024" in above example).

As an aside, it might be possible verify (and possibly update) the copyright date-range in files using information stored in git.

Back to Sander's suggestion: no, I don't believe we should have a consistent copyright date-range on all files because this would be inconsistent with (what I've seen as) common practice with other projects.

**Comment by prjemian** [comment]
[Every year](https://github.com/nexusformat/definitions/issues?q=is%3Aissue+update+copyright+is%3Aclosed), I have updated the final copyright year throughout the project.  Most recently in #1355.  See [`utils/update_copyright_date.py`](https://github.com/nexusformat/definitions/blob/main/utils/update_copyright_date.py) for details.  This script does not touch the starting date.

**Comment by prjemian** [comment]
Regarding the lack of gaps in the range, this script assures that NeXus asserts continuous copyright from starting date inclusive to the present.

**Comment by yayahjb** [comment]
Dear Aaron,
  A copyright statement is a statement of fact about what entity legally
holds the various rights to copy the work,
prepare derivative works, distribute copies, etc.  According to
copyright.gov, "Copyright is a type of intellectual property that
protects original
works of authorship as soon as an author fixes the work in a tangible form
of expression. In copyright law, there are a lot of different types of
works, including paintings, photographs, illustrations, musical
compositions, sound recordings, computer programs, books, poems, blog
posts, movies, architectural works, plays, and so much more!"
 This sounds simple, but is actually very complex, especially when foreign
governments get into the act, since different countries have
different laws, treaties, etc.  For us the interesting thing is that the
success of the open source software movement is based on careful
application of copyright law.  If you don't want to get tangled up in messy
legal disputes, consult with a lawyer and follow their advice.  That being
said, be absolutely certain you tell the truth to the lawyer about who
created whatever works you are discussing and when they created it. Making
a mess of copyright statements by generating them thoughtlessly because it
is convenient to do so is downright foolish.
  Feel free to show this message to LBL counsel.
  Regards,
    Herbert

**Comment by prjemian** [comment]
Always good to have a contemporary review. I've been following the practice
recommended to me years ago by legal counsel here.
