### ISSUE TITLE
recursion exists within NXgeometry base class

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#263]
**Original reporter**: *[prjemian](https://github.com/prjemian)*

In the NXgeometry base class, a recursion exists within the base class definitions of NXorientation and NXtranslation.  In both classes, an NXgeometry group is provided to describe a link to another NXgeometry group if the item is using a relative position.

Is this feature in use?

**Comment by zjttoefs** [comment]
I don't think it is in use. I've yet to see an example of a NeXus file making full use of NXgeometry.
Since we have that deprecated now, there is a chance that day will never come for me.

If the recursion is a problem, we might be able to fix that without breaking anything. If not, with the deprecated status NXgeometry has we've already established we don't like it.
