### ISSUE TITLE
implement difference in rules between base classes and application definitions

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#266]
**Original reporter**: _[prjemian](https://github.com/prjemian)_

Through discussions (teleconferences, private email, and #265), it becomes clear that base classes and application definitions have some differences in their rules that are not represented currently in the nxdl.xsd.  For example, the default settings the "minOccurs" attribute (for fields and groups) is zero for base classes but is one for application definitions.
- base classes enumerate the fields and groups that might appear
- application definitions declare the fields and groups that must appear

**Comment by prjemian** [comment]
needs a fresh start, perhaps discussion first

**Comment by zjttoefs** [comment]
At least a summary of the status now would help.

**Comment by prjemian** [comment]
The current status is indefinite, work was begun but did not result in a fruitful result, mostly because the amount of work necessary to create separate XSD files for base classes and application definitions (and then some combination of both for contributed definitions) grew too large.  I decided it was time to stand back from further investment in this branch (issue_266), reconsider the original question in this issue, and restart with a new branch.

**Comment by zjttoefs** [comment]
cnxvalidate now works around this by implementing it's own hardcoded logic. It is probably not desirable.
