### ISSUE TITLE
Introduce interfaces to base classes

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/definitions#269]
**Original reporter**: *[mkoennecke](https://github.com/mkoennecke)*

Instead of recursion, interfaces will be used for two purposes:
1. To describe fields shared by many components
2. To further subdivide base classes which describe to many 
   different pieces of equipment

**Comment by mkoennecke** [comment]
At NIAC 2014 we decided to make this an experimental chapter in the manual. 
During the move from svn to github the original interfaces branch was lost.

**Comment by mkoennecke** [comment]
There is now a interfaces section at the end of the manual. It can be viewed when checking out the 
interfaces2015 branch. I decided to leave it in a separate branch because otherwise there would have 
been conflicts with the base classes used at other places in the manual.  Also, this reduces confusion 
for readers who are not aware of the discussion. I belatedly became aware that there is an old interfaces branch. This can go now.
