### ISSUE TITLE
express that CIF style is the preferred method for expressing geometry in the manual(s)

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#368]

**Comment by zjttoefs** [comment]
I would consider that done Pete, agreed?

**Comment by prjemian** [comment]
The text is in the design.rst file, in the second paragraph of the "NeXus Coordinate Systems" section.  That paragraph could be promoted to the first paragraph so the message is not buried under the history described in the first paragraph.

Otherwise, this work is complete unless someone can describe where else inn the manual this should appear.
