### ISSUE TITLE
manual: suggest to remove description of XML as a datafile container

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#441]
In one (or more) place in the manual, there is still description of XML as a datafile container.  Suggest this be removed (or commented that XML data files are deprecated).

see 5th paragraph here:
http://download.nexusformat.org/doc/html/motivations.html?highlight=motivation#unified-format-for-reduction-and-analysis

**Comment by zjttoefs** [comment]
I would not remove the entire paragraph, but tone it down at the end.
There are now features in NeXus that do not work in the XML representation.

I would however, remove this Common Data Exchange Format section that follows. First because there is the competing APS Data Exchange Format in HDF5 that we could be confused with. And more important: It looks as if in principle all file formats are born equal. In that they, like for lossless image formats, contain the same information presented in a different way. Our claim should be that we're the only ones to contain the full set of data and metadata at the moment. And finally, none of these converters that the section advertises have come to existence until now.

**Comment by prjemian** [comment]
agreed

**Comment by zjttoefs** [comment]
Feel free to reopen if I missed something or there is other disagreement.
