### ISSUE TITLE
Attribute descriptions for NXroot

### ISSUE THREAD

**Issue by rayosborn** [nexusformat/definitions#466]
The NXDL file or NXroot specifies a number of attributes that define the version numbers of the NeXus API, HDF5 library, etc. used in creating the file. Several of them have the same text description, i.e., "Version of NeXus API used in writing the file".

**Comment by prjemian** [comment]
The definitions of these attributes need to be much clearer. The version of
the NAPI, if it was used should be defined as the NAPI_version and the
version of the definitions specification should be described separately.

Also to note is that none of these attributes are required.
On Apr 24, 2016 8:48 AM, "Ray Osborn" <notifications@github.com> wrote:

The NXDL file or NXroot specifies a number of attributes that define the
version numbers of the NeXus API, HDF5 library, etc. used in creating the
file. Several of them have the same text description, i.e., "Version of
NeXus API used in writing the file".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/nexusformat/definitions/issues/466>

**Comment by rayosborn** [comment]
We also use h5py and, some of us, the nexpy/nexusformat Python API, so there are a plethora of version numbers we could be supplying, so many that they probably cease to be useful except to guide debugging, i.e., I think it's okay to encourage storing them, but they are probably not very useful in writing software.

**Comment by rayosborn** [comment]
One minor suggestion is that instead of writing "Version of HDF (version 5) library used in writing the file", we change it to "Version of HDF5 library used in writing the file." I think the HDF team want us to specify HDF5 as a separate product.

**Comment by prjemian** [comment]
good
