### ISSUE TITLE
consider one-line summaries for application definitions and contributed ones

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/definitions#469]
After the success with #270

**Comment by prjemian** [comment]
These commits were made to the master branch and need to be moved to a new branch to become part of a pull request before being merged into the master branch.  Need to revert the master branch history for it this action.

Others who fetched since 364d958 should do a ``git fetch`` before continuing work on the master.

Following this help (http://stackoverflow.com/questions/18082830/reverting-a-series-of-pushed-merges-and-commits-in-git-without-rewriting-histor), used these commands:

	git clone https://github.com/nexusformat/definitions
	cd definitions/
	git branch issue_469
	git checkout issue_469
	git branch -f master 5df54d1
	git push -f origin master

**Comment by zjttoefs** [comment]
I see no ill effects and it's much nicer!
