### ISSUE TITLE
application definition for data from SPEC

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#477]
describe how data converted from the SPEC data file format can be coded in NeXus

SPEC can write HDF5 data directly or a tool such as spec2nexus can convert SPEC files to NeXus

this NXDL application definition will coordinate that

**Comment by prjemian** [comment]
NXDL is valid with XML Schema

**Comment by mkoennecke** [comment]
Hi Pete,

Am 16.06.2016 um 20:56 schrieb Pete R Jemian <notifications@github.com<mailto:notifications@github.com>>:


NXDL is valid with XML Schema

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/nexusformat/definitions/issues/477#issuecomment-226580124>, or mute the thread<https://github.com/notifications/unsubscribe/AEy_2ozxQpfxyifus3yXqXUS7XjT2wXyks5qMZxcgaJpZM4I3rnK>.


I have now looked at the SPEC application definition in some  more detail. Unfortunately I have
a number of comments:

* Can we put the SPEC user into a NXuser group?
* The counter_basis, M, T fields could be mapped to a control,NXmonitor group at entry level. We have fields
   for mode and preset there.
* The intensity_factor IMHO belongs into the NXdata. And can it be applied on conversion? Needs a new name to in NXdata.
* Apparently (some guess work involved) the NXdata will hold an array for each column. If this is so, please make clear in
  the docs
* It is not clear to me from the docs what thinks like the counter_cross_reference, positioners_cross_reference, the G, NXnote group,
   the positions group mean. If we stick to the self describing nature of NeXus I think these items should be more thoroughly
  documented. Such that even someone who does not know SPEc can deal with it.
* The G group seems to have to do something with geometry. Is there enough information to go for NXtransformations?

Best Regards,


    Mark

**Comment by prjemian** [comment]
Mark:

Thanks for the review.  I believe most of what you suggest can be easily
satisfied.  The NXspecdata will be improved by this.

Relocating the intensity_factor is fine, that makes sense to me now that
you point it out.
I'm not going to impose that it be applied to the intensity data for a
variety of reasons (1: only some analysis software actually want such a
number and that software will apply it, 2: exactly *which* data columns
should or should not get this is not identifiable from the SPEC file).

Improvement of the G group is its own ticket (
https://github.com/prjemian/spec2nexus/issues/51).  The terms involved do
not fit the scenario of NXtransformations.  In some cases, G contains the
UB (orientation) matrix and other items, as defined by the SPEC instrument
support.  Surprisingly, the name of the instrument support is not a defined
term in the SPEC data file and cannot be easily learned after the fact.
Takes some AI and then some good guessing.

Pete

**Comment by prjemian** [comment]
The content of the G group might be better placed in NXcrystal, once its terms are parsed into key:value pairs.  Example are the terms to define the orientation matrix as UB matrix.

**Comment by prjemian** [comment]
* [ ] NXuser: 510b2b25ba345a33e9b3d3c1296c903e355e283d
* [ ] NXmonitor: 243de8d2292ae143689a15158581d7c6275cb7ab
* [ ] intensity_factor: 
* [ ] NXdata documentation about how scan data is to be stored
* [ ] documentation for counter_cross_reference
* [ ] documentation for positioners_cross_reference
* [ ] documentation for the G group
* [ ] documentation for the positions group 
* [ ] documentation for other NXnote groups

**Comment by prjemian** [comment]
Let's leave this open until the checklist is migrated to a new issue

**Comment by prjemian** [comment]
* [x] check list created
* [x] issue closed
