### ISSUE TITLE
Create structure to incorporate PDB definitions into NeXus

### ISSUE THREAD

**Issue by yayahjb** [nexusformat/definitions#553]
As per March 2017 HDRMX meeting in Lund, create a structure to incorporate PDB definitions into NeXus, possibly as a new NXpdb base class.

**Comment by zjttoefs** [comment]
Herbert will discuss at the ACA meeting 26th May. If there could be some idea of how we want to implement that, that would be good.

**Comment by prjemian** [comment]
@yayahjb : bump

**Comment by mkoennecke** [comment]
I had a look at this. Looks good for the time being. But I would like to see an example where a more completed PDB file has been mapped.

Then I have a suggestion: Currently the NXpdb class s used for the main entry and for all groups underneath it. I suggest to name the top level NXpdb_container in order to mark it more clearly as a the root of a hierarchy following NeXus PDB conventions.

**Comment by yayahjb** [comment]
As per NIAC 2018, have added example files, in [nexusformat/exampledata/nxpdb](https://github.com/nexusformat/exampledata/tree/master/nxpdb), produced using the conversion tool in CBFlib.  Will extract the conversion tool, package it and put it in nexusformat by next week.

**Comment by prjemian** [comment]
2020 Code Camp decide to close this issue as resolved by PR #614.
