### ISSUE TITLE
add choice element to NXDL

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#619]
As part of [adding new geometry definitions to `NXdetector`](https://github.com/nexusformat/definitions/pull/601), it is proposed to extend the NXDL to allow for specification of multiple choices for a named group or field.  

The proposed use seems clear, to create a group with a defined name that is one specific NXDL class from a list of possibilities.  The immediate children of the `<choice>` should all be of the same type (either all `<field>` or all `<group>` elements) and all should have the same `@name` attribute.

**Comment by prjemian** [comment]
See the two examples of `<choice>` highlighted in commit a55aa9c .

**Comment by prjemian** [comment]
created branch ["choice_element_619"](https://github.com/nexusformat/definitions/tree/choice_element_619) for this work

**Comment by zjttoefs** [comment]
This has code (in a branch), so should probably go into the next milestone, if possible.

**Comment by prjemian** [comment]
@matthew-d-jones , @zjttoefs , @mkoennecke 

The [example code](https://github.com/nexusformat/definitions/pull/601/commits/a55aa9c41be91cd80faf74c1b729a6c225be2223#diff-2f1b96d59d400c9ec5ef598639fe9f7bR736) shows:

```
<choice>
    <group name="pixel_shape" type="NXoff_geometry">...</group>
    <group name="pixel_shape" type="NXcylindrical_geometry">...</group>
</choice>
```

To ensure that the `@name` attribute is defined once, I'm going to change that syntax to:

```
<choice name="pixel_shape">
    <group type="NXoff_geometry">...</group>
    <group type="NXcylindrical_geometry">...</group>
</choice>
```

Now, the `@name` attribute is defined once and we *know* that any of the choices must have only that name.

**Comment by prjemian** [comment]
test the revised schema using this command:

    xmllint --noout --schema nxdl.xsd contributed_definitions/NXpete.nxdl.xml

**Comment by prjemian** [comment]
before we close this ticket, update the documentation

**Comment by prjemian** [comment]
* end of `defs_intro.rst`
* autogenerated content in `nxdl_desc.rst`

**Comment by zjttoefs** [comment]
There is no __need__ for `choice` for fields __now__. I can easily see this for the future, but I am happy to wait for the code until we cross that bridge.

The changed syntax to me isn't better or worse for this current use case. I've not looked into it in detail, but it does not less flexible. Can you only have a choice between things that are supposed to have the same name now? I can come up with a good example, but for transitioning to newer versions of the definitions you could have a `choice` between _old_scheme_ and _new_scheme_ (NXgeometry vs NXtransformation maybe), where the names don't have to be the same. 
I'm mainly checking I understand it correctly, because all we want to have right now appears to work.

**Comment by prjemian** [comment]
Your example of a this-or-that choice with *different* names is already covered by the existing NXDL Schema, isn't it?  One defines the two components and makes them both optional.  The existing NXDL Schema does not cover the case where we *must* have one or the other.
