### ISSUE TITLE
discuss NIAC2018Minutes.md

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#641]
discussions about items in the [NIAC2018 minutes](https://github.com/nexusformat/wiki/blob/master/content/NIAC2018Minutes.md)

**Comment by prjemian** [comment]
> Proposal: allow the `default` attribute for any NeXus group which contains a plotable NXdata.

This implies we might have both `default` and `signal` attributes in any NeXus group if plottable data exists.  The `default` attribute points the next step in the path to the default plottable data group.  The `signal` attribute points to a plottable dataset.  We should amend this to read:

> Proposal: allow the `signal` attribute for any NeXus group which contains a plotable NXdata.

**Comment by mkoennecke** [comment]
I agree with you that this implies that any group can have a signal attribute. However, in the minutes I am supposed to record what we actually voted on. And in my recollection we did not specifically mention the signal attribute in the proposal. If my recollection is wrong, please correct me. Otherwise, for that reason, I am hesitant to modify the minutes.

**Comment by vasole** [comment]
I think there is a misunderstanding. Any group can have a default attribute pointing to an NXdata group. That does not imply the referring group must have a signal attribute anywhere. The pointed NXdata group by the other hand is expected to have that signal attribute since it is expected to follow the new style NXdata convention (after all it is a new feature).

**Comment by vasole** [comment]
There is no difference with current behavior. NXentry is a group, has a default attribute and does not need any signal attribute. I hope that clarifies things.

**Comment by prjemian** [comment]
Armando

Yes, that clarifies.  The default attribute can appear in any group that is
not NXdata.

Thanks,  Pete

**Comment by prjemian** [comment]
There are other items in the [NIAC 2018 minutes](https://www.nexusformat.org/NIAC2018Minutes.html) to file as issues for the 2020-2 Code Camp.  See the section headings with these titles:

* **NXdata auxiliary signals** (#)
* **Attribute Mask and Normalisation** (#)
* **Extended Use of the Defaults Attribute** (#812)
* **NXenvironment** (#)

**Comment by prjemian** [comment]
Separate issues created, closing here.
