### ISSUE TITLE
Allow strings in NXlog?

### ISSUE THREAD

**Issue by matthew-d-jones** [nexusformat/definitions#687]
The `value` dataset in `NXlog` is documented as type `NX_NUMBER`, but it would be useful to us to use it for strings too.
Any reason we should not change it to `NX_ANY`?
Interestingly the documentation for `NX_ANY` explicitly mentions logs as a use case...

**Comment by zjttoefs** [comment]
NXnote mentions logs. I like the fact that quantifies are numbers + units that are universally understood and people cannot start "logging" temperatures of "300 K".

What is the real-world use case? If it is system logs, then we should make a separate class.

**Comment by SkyToGround** [comment]
The NeXus standard is not necessarily very clear on how its various "constants" can be applied/used but it is my understanding that `NX_ANY` is meant to indicate possible units and not possible data types. Hence the solution for allowing strings in NXlog would then be something along the lines of replacing `value: (optional) NX_NUMBER {units=NX_ANY}`with `value: (optional) NX_NUMBER {units=NX_ANY}, NX_CHAR` on the [NXlog documentation page](http://download.nexusformat.org/doc/html/classes/base_classes/NXlog.html#nxlog).

**Comment by zjttoefs** [comment]
I am against turning NXlog into something that cannot be interpreted (=arbitrary strings). That is why we have a standard. But maybe there is a use case I am not seeing. Hence the "awaiting input".

**Comment by SkyToGround** [comment]
I have two use cases for allowing strings in NXlog:

1. Log messages
We have long discussed the fact that we want to store some clear text log messages to the NeXus files. One (possible) example would be to store some information from the accelerator control room, e.g. `Accelerator power will decrease from 2 MW to 1 MW between 18:00 and 19:00.`
The (weak) arguments against using `NXnote` are that the `date` field does not allow timestamps as anything other than strings and that the documentation does not necessarily (explicitly) allow for the fields (in this case `date`, `type`, `data`) to be arrays.

2. EPICS updates
The channel access and pvAccess EPICS protocols allows for the `VAL` field to be in the form of a string. Thus the `f142` flat buffer schema is also able to store its value as a string and the `f142` writer module can write those strings to the `value` field of a `NXlog`. By not allowing "value"-strings in NXlog, the string functionality will have to be removed from the `f142` writer (and possibly schema).
I am actually for that but it does result in us making "braking changes" to the interface of the file-writer. In practice it seems to me that no-one would be affected by those breaking changes as the current string-writing functionality in the file-writer is somewhat broken anyway (I am surprised if anyone uses it).

**Comment by zjttoefs** [comment]
The log messages are for human consumption. Most NXlogs are not. Having a different class (with log timestamps) makes sense, as I stated above. NXlog_message maybe?

The EPICS example is not a "use case" as we still don't know what information is proposed to being written. Creating ambiguity at the consumer end in order to keep the implementation completely generic isn't great.

**Comment by prjemian** [comment]
On 2019-09-16 7:42 AM, Jonas Nilsson wrote:
> The NeXus standard is not necessarily very clear on how its various 
> "constants" can be applied/used

This is not true.  The NeXus standard is explicit in the use of NX_ANY. 
NX_ANY ("units for things like logs that aren't picky on units") is a 
member type of the "anyUnitsAttr" which documentation states:

    "Unit categories in NXDL specifications describe the expected type 
of units for a NeXus field."

- ref: 
https://github.com/nexusformat/definitions/blob/acf729e9ec99f69e7d3f42e1d143cf9e1538be17/nxdlTypes.xsd


The valid data types are enumerated elsewhere in the same file under the 
simpleType "NAPI".  See: 
https://github.com/nexusformat/definitions/blob/acf729e9ec99f69e7d3f42e1d143cf9e1538be17/nxdlTypes.xsd#L447


We must be conservative about changing the intent of existing NeXus 
definitions, especially base classes.  We cannot easily assess how much 
end-user software has been written that expects the value field to be 
other than NX_NUMBER.  A *strong* case must be made to make such a 
change.  It makes perfect sense to consider NXlog ("Information recorded 
as a function of time") for logging a time-series of text values. 
NXnote ("Any additional freeform information not covered by the other 
base classes.") might be an alternative.

Since this is the first such proposition to use NXlog for a time-series 
of strings, might a "text_value" field be used?  This would not break 
existing use and provide a way forward.

Pete

**Comment by SkyToGround** [comment]
@prjemian Seeing as we are going off topic here anyway. I wanted to comment a bit on your comment.
You are correct in the best way ([technically](https://www.youtube.com/watch?v=hou0lU8WMgo)). What I meant to say was that the NeXus standard is in many cases hard to read at a glance (i.e. it has poor self-documentation). The evidence for this is the mistake that Matt and others (including me) have done.

Some possible solution to this particular problem follows:
- Using different fonts for units and types.
- Putting the structures in tables with separate columns for units and types.
- Using the prototypes `NX_UNIT_` for units and `NX_TYPE_` for types.
- Rename `NX_ANY` to `NX_ANY_UNIT`.

**Comment by prjemian** [comment]
Great suggestions!  (Use of a table was an earlier version of the documentation.)  Easiest of the with least impact on the standard is to use different fonts for units and types.

**Comment by zjttoefs** [comment]
Looks like to consensus is to either extend NXnote to have timestamp or to generate a derivative class NXlog_messages to hold such information.
