### ISSUE TITLE
Clarify the nature of NeXus classes described by Application Definitions

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#697]
From Steve Collins, the chair of DLS's NeXus working group,

```
The nature of NeXus classes described by Application Definitions.

The question is, for what purpose are NeXus classes described by application definitions, where they are 
already described independently? 

Specific questions:

a.	Can instances of classes inside definitions require new fields that were previously optional?

b.	Can instances of classes inside definitions make optional new fields that were previously not 
mentioned? (E.g. ‘depends_on’ in NXsample/NXmx)

c.	Can instances of classes inside definitions require new fields that were previously not 
mentioned?

d.	If the answer to all three is ‘yes’ then can we view the process of defining classes within an 
application definition as defining a subclass of the original class? That is, all instances of the class 
within the definition are valid instances of the original class, but not vice-versa?

Also, how can application definitions be extended? We will probably want to use the NXmx definition but add optional fields for the sample surface orientation and the response of a polarization analyser (Jones matrix). NXmx contains just about everything else that we can think of for physical science diffraction applications such as magnetic and surface diffraction. Can we propose to achieve a new Application Definition by formally extending NXmx?
```

**Comment by prjemian** [comment]
The distinction between base classes and application definitions and contributed definitions is described here: https://manual.nexusformat.org/classes/index.html

> NeXus base class definitions define the set of terms that might be used in an instance of that class. Consider the base classes as a set of components that are used to construct a data file.

> NeXus application definitions define the minimum set of terms that must be used in an instance of that class. Application definitions also may define terms that are optional in the NeXus data file.

> NXDL files in the NeXus contributed definitions include propositions from the community for NeXus base classes or application definitions, as well as other NXDL files for long-term archival by NeXus. Consider the contributed definitions as either in incubation or a special case not for general use.

**Comment by prjemian** [comment]
Specific questions:

> Question a. Can instances of classes inside definitions require new fields that were previously optional?

A: Yes.  That is one of the motivations to have application definitions.  By default, all content in an application definition is required.  This example requires 1 and only 1: https://github.com/nexusformat/definitions/blob/0eeaea50c3818749093a9abc065118ce23427e43/applications/NXcanSAS.nxdl.xml#L940

> Question b. Can instances of classes inside definitions make optional new fields that were previously not mentioned?

A: Yes.  To make it optional, set attribute `minOccurs="0"`.  Example: https://github.com/nexusformat/definitions/blob/0eeaea50c3818749093a9abc065118ce23427e43/applications/NXcanSAS.nxdl.xml#L542

> Question c. Can instances of classes inside definitions require new fields that were previously not 
mentioned?

A: Yes  Example: https://github.com/nexusformat/definitions/blob/0eeaea50c3818749093a9abc065118ce23427e43/applications/NXiqproc.nxdl.xml#L92

> Question d. If the answer to all three is ‘yes’ then can we view the process of defining classes within an application definition as defining a subclass of the original class? That is, all instances of the class 
within the definition are valid instances of the original class, but not vice-versa?

A: Hesitantly, I say yes.  Hesitant because NeXus is not specifically object oriented.  The super class might be either NXentry (for single-technique data, such as SAXS) or NXsubentry (for multi-technique data such as SAXS/WAXS or SAXS/SANS or ...).  If you are thinking of a new application definition that uses another as a starting point (lie a super class), then there is an `extends` attribute in the `definition` element of the NXDL file: https://github.com/nexusformat/definitions/blob/0eeaea50c3818749093a9abc065118ce23427e43/applications/NXarpes.nxdl.xml#L24 which describes this relationship.  For almost (waffling here) all NXDL files to date, they extend the [`NXobject` ](https://manual.nexusformat.org/classes/base_classes/NXobject.html#nxobject) base class, *the base object of NeXus*.

**Comment by prjemian** [comment]
Might any of these questions be good additions to the [FAQ](https://manual.nexusformat.org/faq.html) section?

**Comment by prjemian** [comment]
FAQ: https://manual.nexusformat.org/faq.html

**Comment by prjemian** [comment]
@PeterC-DLS : If you agree, once these questions are added to the FAQ, I'll close this issue.
