### ISSUE TITLE
How to set the title of an NXdata?

### ISSUE THREAD

**Issue by vasole** [nexusformat/definitions#760]
I am missing a way to set the title of an NXdata plot. I can suggest the labels via the ``@long_name`` attribute but I miss the equivalent thing for the plot title.

Is there a solution existing/envisaged?

**Comment by rayosborn** [comment]
In NeXpy, we have for years looked for a text field called 'title' in the NXdata group. If one isn't there, it looks for 'title' in the parent NXentry group, with a fallback to displaying the path to the NXdata group. I was surprised to see that it is not reflected in the base class documentation for NXdata as well as the NXentry because I thought that had been agreed years ago, but I may be wrong. I would suggest we add a 'title' field to the NXdata base class.

**Comment by vasole** [comment]
Perfect.
