### ISSUE TITLE
[NXtomo] Need user flags

### ISSUE THREAD

**Issue by vasole** [nexusformat/definitions#762]
The NXtomo definition foresees three flags in the image_key dataset (projection = 0, flat field = 1, dark field = 2, invalid = 3). We need to add some additional keys to indicate other uses (for instance control images).

When dealing with detectors, the possibility to use user_defined masks was foreseen but it is not the case for this definition. We would not like to take a number that later on is used by NeXus. Because of that we have started to use negative numbers to indicate user specific meaning. Could that approach (flags smaller than 0 are available for the user) be officially endorsed or an alternative suggested?

**Comment by vasole** [comment]
By an alternative I mean things like flags bigger than XX are free for the user.

**Comment by mkoennecke** [comment]
Armando,


Am 05.03.2020 um 09:03 schrieb V. Armando Solé <notifications@github.com<mailto:notifications@github.com>>:


The NXtomo definition foresees three flags in the image_key dataset (projection = 0, flat field = 1, dark field = 2, invalid = 3). We need to add some additional keys to indicate other uses (for instance control images).

When dealing with detectors, the possibility to use user_defined masks was foreseen but it is not the case for this definition. We would not like to take a number that later on is used by NeXus. Because of that we have started to use negative numbers to indicate user specific meaning. Could that approach (flags smaller than 0 are available for the user) be officially endorsed or an alternative suggested?

This could be done but needs some more opinions from NIAC. But I would rather prefer to give more numbers in image_key meaning. Especially when these
additional image keys are of general interest.


Regards,

     Mark Koennecke

**Comment by vasole** [comment]
If to add control frames is a common practice, then I agree it would be best to add an additional number.

**Comment by benajamin** [comment]
This was discussed in the [April 2020 telco](https://www.nexusformat.org/Telco_20200424.html). We agreed that reserving negative image keys for user-defined cases is a good strategy, but there should also be additional fields (perhaps in a groups to collect them together) to provide a standardised method to record the meaning of these keys. An example could be:
user_keys:NXgroup
   minus_1: NXnote - "timing control"
   minus_2:NXnote - "laser pulse"

We recommend writing a NIAC proposal for amending the NXtomo application definition in such a manner.
