### ISSUE TITLE
Schema URL in NXDL template file

### ISSUE THREAD

**Issue by matumot** [nexusformat/definitions#835]
Hello,

I looked NeXus tutorial page:
https://manual.nexusformat.org/applying-nexus.html

Then I could not access URL for http://definition.nexusformat.org/nxdl/3.1
written in the NXDL template file.

Is it need to be fixed?

**Comment by PeterC-DLS** [comment]
All the xsd and xml files have the schema location so I guess we should ensure it is valid.

**Comment by prjemian** [comment]
This is a great question since it involves an obscure detail of the XML language.  The *URI* in the question is used in the header of every NXDL file, such as this example from *NXentry*:

```
<definition name="NXentry" 
	type="group" 
	extends="NXobject"
	category="base"
	xmlns="http://definition.nexusformat.org/nxdl/3.1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"
	>
```

It's this line:  `xmlns="http://definition.nexusformat.org/nxdl/3.1"`

### Short answer

It's not a URL, it's a URI (https://danielmiessler.com/study/difference-between-uri-url/) and it does not need to be an accessible link.

### Explanation

This web site describes the situation (https://www.w3schools.com/XML/xml_namespaces.asp) for the `xmlns` attribute.  It says:

> When using prefixes in XML, a namespace for the prefix must be defined.
> The namespace can be defined by an xmlns attribute in the start tag of an element.
> The namespace declaration has the following syntax. xmlns:prefix="URI".

Further down on that page, it says:

> **Note**: The namespace URI is not used by the parser to look up information.
> The purpose of using an URI is to give the namespace a unique name.
> However, companies often use the namespace as a pointer to a web page containing namespace information.

In our case, NeXus uses this _URI_ to define a unique namespace but has chosen not to create a _URL_ (web address) for this.  The history on this URI goes back more than a decade (see #55).  Originally, it was planned to have the NXDL version be the last part of the URI (the `/3.1` part as shown).  In https://github.com/nexusformat/definitions/issues/387#issuecomment-222720311, it was decided to leave this constant (for reasons described in https://github.com/nexusformat/definitions/issues/387#issuecomment-158234907).

**Comment by prjemian** [comment]
And the same URI is used when specifying the schema location:

    xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd"

Again, the URI is given first but is never checked by any software.  The path to the schema file (`../nxdl.xsd`) is the second part.

**Comment by prjemian** [comment]
Does NeXus want to create a URL that matches this URI?  Since most web browsers mark `http://` pages as insecure, it may be problematic to maintain such a page.

@FreddieAkeroyd Is it possible to create a page for this url: `http://definition.nexusformat.org/nxdl/3.1`?  We could it fill it with a description of where to get info about the NXDL language and class files, and also maybe the explanation from above.

**Comment by matumot** [comment]
Thank you for  providing the information.
Freddie-san says we used to have that URL and it pointed to a directory of the actual nxdl files,
and make the URL  http://definition.nexusformat.org/nxdl/3.1 to be accessible.

**Comment by FreddieAkeroyd** [comment]
@matumot @prjemian You should now see files at http://definition.nexusformat.org/nxdl/3.1

**Comment by FreddieAkeroyd** [comment]
We should probably update the 3.1 number at some point...

**Comment by FreddieAkeroyd** [comment]
@prjemian should we update 3.1 to the release number each release?

**Comment by matumot** [comment]
Thank you. Now I could see xml schema files.
I have one question.
Accessible files seem to be simplified one, and not to be the actual files with xml format.
I think it is readable and acceptable. 
But is it OK ?

**Comment by prjemian** [comment]
We could change the URI to one that is not version-based.  This affects XML file validation as it describes the rules on which the NXDL language is based.  We have not proposed anything that would change those rules.

**Comment by prjemian** [comment]
This URI http://definition.nexusformat.org/nxdl/3.1 (now a URL), shows the tree view of each of the NXDL files.

**Comment by matumot** [comment]
OK. I  would like to close the issue.
