### ISSUE TITLE
NXDL: Can an attribute have an enumeration?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#900]
The CI fails for #681, PR#897, (https://github.com/nexusformat/definitions/pull/897/checks?check_run_id=2174237409) when an **attribute** is defined with an **enumeration** specifying the only allowed values.  Apparently, the NXDL schema does not permit this now.  Can this be fixed?

**Comment by benajamin** [comment]
The schema says that an [attribute can have an enumeration](https://github.com/nexusformat/definitions/blob/96aad4c6ad880e69d92b0c81971902baed846d51/nxdl.xsd#L959). CI is not failing for #897 now so that problem (whatever it was) has been fixed. There doesn't seem to be anything left to do except close this issue.
