### ISSUE TITLE
NXmx: Definitions for multi-channel (thresholds) data

### ISSUE THREAD

**Issue by soph-dec** [nexusformat/definitions#940]
It is currently undefined how to write data with images from more than one channel (for example multiple thresholds or difference images).

A possible solution we see is to extend the [data field](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-data-data-field) by one dimension, i.e. data[nP, ch, i, j, k], where "ch" denotes the channel. However, there are still some open questions regarding this approach:

**How can the "ch" be identified?**
If for example two threshold images are taken and one difference image, how can they be identified? 
  
**How can the "ch" index be connected with associated metadata like flatfield, pixel mask or threshold energy?**
One problem is that this metadata is not given/defined for every channel, so there will likely not be a 1:1 relation. For example, taking an image with difference mode means two threshold images are taken, one with low and one with high threshold energy, corrections like flatfield and pixel masks are applied for each of them and finally the difference image is caclulated from the corrected threshold images. That means not one, but two threshold energies are associated with that data, but no pixel mask or flatfield - but having that metadata might still be useful for the user.

Regarding the first question, we were wondering if perhaps the [dimension scale definition](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-variable-field) could be extended to also take a list of strings, not only numbers - then we could annotate the channels there. However, we are unsure if this is the right place to store this kind of information since the [axes attribute](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-data-axes-attribute) is tied to the default plot. Furthermore, this does not solve the second question.

A more general solution for both questions could be the introduction of a new group "channel", where the corresponding indices of the data and also the associated metadata (either directly or also via indices and links to the proper fields) could be stored. A clear advantage of this solution is that it can be easily extended for future purposes.
For example, this could look like this:
```
/data/channel/th_1/@index = 0
/data/channel/th_1/threshold_energy
/data/channel/th_1/flatfield
/data/channel/th_1/pixel_mask
/data/channel/th_2/@index = 1
/data/channel/th_2/threshold_energy
/data/channel/th_2/flatfield
/data/channel/th_2/pixel_mask
/data/channel/diff/@index = 2
/data/channel/diff/threshold_energy_low
/data/channel/diff/threshold_energy_high
```

What are your thoughts regarding these solutions? Do you maybe have other suggestions how to handle these cases?

**Comment by soph-dec** [comment]
Considering the suggestion from @yayahjb and the comment above, @kalcutter and me worked out a more refined proposal.

We suggest adding two attributes to the [data field](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-data-field): 
- `channels`: array of strings containing the names of all channels present in the image data in the correct order, i.e. its length must match the size of the channel dimension in the data

- `channel_source` points to a `DATA_channel` group (DATA denoting the name of the data as in `/entry/data/DATA`) located in the `NXdetector` group. `DATA_channel` contains the channel information, all elements of the `channels` array must be present as fields of type `NXdetector_channel`, but it may contain more.

This approach offers enough flexibility for the usecases we currently have and is also easily extendable. For example, we have cases where only a difference image is requested, but of course it is desireable that the metadata of the corresponding threshold images is still available.

For example, for the difference only case
```
/entry/data/data1
  @channels = ["diff"]
  @channel_source = "/entry/instrument/detector/data1_channel"
```

as well as difference plus both threshold images case

```
/entry/data/data1
  @channels = ["th_1", "th_2", "diff"]
  @channel_source = "/entry/instrument/detector/data1_channel"
```

the `data1_channel` group would contain all three fields (of type `NXdetector_channel`):
```
/entry/instrument/detector/data1_channel
  /th_1
    /threshold_energy
    /flatfield
    /flatfield_applied
    /pixel_mask
    /pixel_mask_applied
  /th_2
    /threshold_energy
    /flatfield
    /flatfield_applied
    /pixel_mask
    /pixel_mask_applied
  /diff
    /threshold_low (link to th_1, for example)
    /threshold_high (link to th_2, for example)
```

The only case we could think of where this approach would not work exactly like this is if there was data combined from multiple devices (i.e. multiple NXdetector groups), but is that even a case that could happen?

**Comment by soph-dec** [comment]
Are there any thoughts/inputs regarding our new propsal?

**Comment by benajamin** [comment]
This proposal could work, but I feel that it adds a lot of complexity that I'd prefer to avoid. NeXus tends to expect that a dataset contains one and only one "thing" at a time. If I understand correctly, you want to extend the metadata to enable describing multiple "things" in a single dataset. An alternative could be to simply split the set of data arrays into separate HDF5 datasets. I suspect that you don't discuss this option because you want the performance advantage of dumping all of the numbers into a single dataset. One way that could allow you to have your cake and eat it too is to use virtual datasets to point to subsets of the "one big dataset" and then use the normal NeXus metadata to describe each of the virtual datasets in turn.
Could the use of virtual datsets solve your issues?

**Comment by soph-dec** [comment]
Thank you for your reply, but virtual datasets don't seem to be the right approach and also do not solve our issues.
First of all, the way we see it, threshold channels are no different from color channels like for example RGB. The data of each channel belongs to the same exposure, are taken with the same detector, have the same timestamp - so it would not be combining different things in one dataset, but keeping data that belongs together in one dataset.
Also with virtual datasets the problem regarding the multiple different flatfields/pixelmasks etc is not solved, adding multiple detector groups does not make much sense, since there is only one detector involved and it would also result in a lot of repetition.

**Comment by benajamin** [comment]
The other side of the discussion is that [NXdata](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata) "describes the plottable data and related dimension scales" and what you are describing is clearly not intended to make a meaningful plot. Further, while the proposed solution is elegant from your perspective, it pushes problems into other areas. Increasing the complexity of parsing the NXdata information affects everyone in the NeXus community and I am sure that there are many (@rayosborn  for one) who will feel that this proposal shoehorns to include a niche feature into the central part of a NeXus data file.
I am of the opinion that NXdata/data doesn't need to be a direct copy of/link to NXdetector/data. Therefore, I'm fine with the proposed channel feature being implemented in NXdetector, but it should stay out of NXdata. I also admit that my opinion is not unanimously shared.

**Comment by benajamin** [comment]
I visited Dectris to discuss the issues raised above and am posting this message to inform others who may be interested. It seems to boil down to 3 issues that don't necessarily have to be linked to each other:

1. Allow the dimension variable values in NXdata to be an array of strings in addition to NX_NUMBER. For example, an axis variable might point to a field in NXdata called "pressure" that holds an array of numerical values that can be used to label the pressure axis of a plot of the measured data. Dectris would like to be able to do the same with a list of strings since the "channels" they want to present are not always well represented by a number.
2. Dectris want to be able to write more information about their detector settings in a meaningful way and that doesn't risk conflicting with NeXus. I recommended making use of a registered [naming prefix](https://github.com/nexusformat/NIAC/issues/49) to add further data to NXdetector. Dectris should formally request a specific prefix that the NIAC can approve for their use.
3. Dectris would like to be able to point to the source of a link. This is the similar to what we originally did with the [@target attribute for links in NeXus](https://manual.nexusformat.org/nxdl_desc.html?highlight=target#linktype), but the way that HDF5 does transparent linking breaks this strategy. I don't think we have an agreed solution at the moment. Perhaps the FIELDNAME_source proposal described above is worth discussing as a way forward.

**Comment by soph-dec** [comment]
Thank you @benajamin for the discussion and the comment above as well as opening the issue regarding the axis labels!

I would just like to add a small example to show how this would look like.
Let's say we have one dataset `data1` in `entry/data`, then the data group would be something like
```
data: NXdata
  @signal="data1"
  @axes=["image_number", "channel", ".", "."]
  @image_number_indices=0
  @channel_indices=1
  data1: uint[10, 3, 1024, 1024]
  image_number: uint[10]
  channel=["threshold_low", "threshold_high", "difference"]
```
In the NXdetector group, we would then have a group of type NXdetector_channel named NAME_channel for every entry NAME in the [VARIABLE](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-variable-field) "channel":
```
detector: NXdetector
  threshold_low_channel: NXdetector_channel
    threshold_energy: float
    flatfield: float[i,j]
    flatfield_applied: bool
    pixel_mask: int[i,j]
    pixel_mask_applied: bool
  threshold_high_channel: NXdetector_channel
    threshold_energy: float
    flatfield: float[i,j]
    flatfield_applied: bool
    pixel_mask: int[i,j]
    pixel_mask_applied: bool
  difference_channel: NXdetector_channel
    threshold_energy: float[2]
```
After some consideration, we agreed that we are fine with dropping the `FIELDNAME_source` attribute. For us, it suffices to have the connection via the field/group names.

**Comment by soph-dec** [comment]
As for the fields of `NXdetector_channel`, we would like to allow a subset of keys available for `NXdetector`, i.e. all that are applicable to individual channels.

**Comment by benajamin** [comment]
@soph-dec To be clear, does your proposal involve the fields within the `NXdetector_channel` group overriding any corresponding fields in the parent `NXdetector` group, for the case of the data corresponding to the channel indicated by the name of the `NXdetector_channel` group?

**Comment by benajamin** [comment]
@soph-dec Does Dectris wish to reserve a field prefix, e.g. `DECTRIS_` so that you can create custom fields in your own namespace? This would allow you more freedom to prototype writing further metadata before proposing extensions and additions to the NeXus standard. Examples of already reserved prefixes are [here](https://manual.nexusformat.org/datarules.html?#reserved-prefixes).

**Comment by soph-dec** [comment]
@benajamin Thank you for your questions!

Yes, we think it makes sense that the fields in `NXdetector_channel` would override the corresponding fields in the parent `NXdetector` group.

Also yes to the question regarding the `DECTRIS_` prefix, we think it could be useful in the future. I will open a separate issue since it is not directly related to this one.

**Comment by benajamin** [comment]
The proposal seems to be missing something that indicates that the values in the "channel" field correspond to the NXdetector_channel groups.

**Comment by soph-dec** [comment]
Thank you for the feedback, we will prepare and open a PR for the proposed changes.

**Comment by phyy-nx** [comment]
Hi all, I've been pointed to Dectris's proposal to resolve this issue, documented here:
https://github.com/dectris/documentation/tree/main/filewriter_v2#multi-channel-data

Shall we review and discuss?  Thanks!

**Comment by yayahjb** [comment]
Yes
