### ISSUE TITLE
NXmx: Change `entry/end_time_estimated` from "required" to "recommended"

### ISSUE THREAD

**Issue by soph-dec** [nexusformat/definitions#966]
For some experiments, it is not possible to estimate an end time. For example when there are multiple triggers in one series, there is no way to give a useful estimate on the end time of the series.

Could [this field](https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-end-time-estimated-field) be changed to "recommended" instead of "required"? Or do you maybe have other suggestions how to handle cases where no real estimate can be given?

Thank you in advance!

**Comment by yayahjb** [comment]
You can always overestimate an end time, e.g. at the end of the beamtime
reserved for the experiment, or if that
is truly impossible, put in an intentionally invalid CIF-style null "." or
"?" string instead of a time.  Remember, this is
just an estimate of an end time, not an actual recorded end time.

**Comment by prjemian** [comment]
If an estimate can always be created, it is not really _required_?  What is the context that makes an estimated value required instead of optional?

**Comment by yayahjb** [comment]
In most data collections the estimate created at the start of data
collection of the end time will be replaced by an actual end time when the
run ends normally, but if the run aborts it can be very helpful to have the
best estimate available, e.g. to have some idea of the likely radiation
damage.  If you don't make an estimate mandatory the chances of it being
skipped and not available in case of an abort increases, so we decided to
make it mandatory.

**Comment by prjemian** [comment]
So, no context requires it to be mandatory.  Then make it optional.

**Comment by yayahjb** [comment]
The context that makes it mandatory is Murphy's Law.  If you don't make
it mandatory then in a significant number of cases (unexpected aborts)
critically needed data is lost.  So for the MX community we agreed to make
it mandatory.  Other communities may make different decisions.

**Comment by prjemian** [comment]
@yayahjb : You have not answered the question.  Why is the `end_time_estimated` "critically needed" once the experiment is finished?

**Comment by yayahjb** [comment]
Because it is critically needed

    1.  When the experiment starts because all we know then is an
estimate of when the experiment will end, and
    2.  After the experiment ends if the experiment ends without a proper
record of the time at which the last frame is actually collected and/or
exposed.

Case 1 always happens
Case 2 sometimes happens, but is very unpredictable, so we have decided
to err on the side of caution

**Comment by soph-dec** [comment]
Thank you for your answers!

If I understand correctly, that means if there is no `end_time` provided after the experiment, the experiment might be regarded as faulty or not completed? If that is truly the case, maybe that could be pointed out in the documentation.

If you think the estimated value should be kept as "required", would you consider defining a default value for cases where it cannot be done? Shouldn't that value be of type `NX_DATE_TIME` to still have it follow the definition?

**Comment by soph-dec** [comment]
I would like to ask a follow-up question. If a field is required, but for some reason the information is not there, is it always accepted to use a "." or a "?"? This is suggested for some fields specifically (allthough "?" is only mentioned in NXpdb as far as I can see), but I could not find any information that this is generally how such cases should be handled. If that is the recommended way to handle that, how should we handle fields that are not of type NX_CHAR?

**Comment by prjemian** [comment]
I stand by my [previous comment](https://github.com/nexusformat/definitions/issues/966#issuecomment-1015753321) that the **need** for _required_ has not been [described](https://github.com/nexusformat/definitions/issues/966#issuecomment-1015768129).  

What scientific analysis process will break if this information is not provided?

**Comment by yayahjb** [comment]
Dear Colleagues,
  This is _not_ a nexus decision.  It is an MX community decision.  I would
suggest you hold off
on making this change and make your case to the MX community.  There is an
HDRMX mailing
list and there is an upcoming ACA meeting in Portland and there will be
future HDRMX meetings.
I would suggest patience.  It took more than 2 decades to get community
agreement on the
gold standard, which is what is reflected in the NXmx application
definition.
  Now to Pete's specific question.  The reason that the estimated time was
made mandatory is that
the actual end time is often not successfully recorded, but since there is
now increasing use of
carefully planned detailed data collection strategies, a fairly accurate
completion time is almost
always available at the start of collection, at least at synchrotron
beamlines.  If you make that
recommended instead of required, you probably will never know you are
failing to record that
information until some failed collection happens.  If you make it required
there is a better chance
you will find out sooner.  IMHO the point of validation is not so much to
tell you that a particular
dataset is missing some particularly vital information, but more to tell
you that your beamline
setup has some information gaps that might cause trouble for data you might
collect in the future.
  Regards,
    Herbert

**Comment by phyy-nx** [comment]
Relevant comment from #1143:
https://github.com/nexusformat/definitions/issues/1143#issuecomment-1227873152

And @soph-dec's response:
https://github.com/nexusformat/definitions/issues/1143#issuecomment-1232914186

From @soph-dec 
>Besides those two, also SOURCE.name, SAMPLE.name and INSTRUMENT.name cannot be known unless the user inputs that information.

So my thought here is that SOURCE.name and INSTRUMENT.name are always known by the beamline running the detector, so they should be populated using some kind of site file or config file.  Likewise, SAMPLE.name is usually known before triggering data collection, and is often available from metadata stores at a facility.  Sometimes it is proprietary but even then keywords or numbers are often used I believe.

The same arguments can be made for BEAM.total_flux and ENTRY.end_time_estimated.  It's not necessarily the job of the detector manufacturer to populate these fields, but total_flux should be available from the facility supplying photons, also often recorded in metadata available to the local programmer automatically, and end_time_estimated should be a derived value from a triggering request, and should be made available to the metadata.

The kind of glue I'm describing that connects a detector to its facility is not necessarily easy to write, but an API from a detector manufacturer that includes fields that are required will ensure that facilities provide those fields and make the final files useful for long term archival.

Thoughts @soph-dec?  Thanks for keeping the conversation going :)

**Comment by yayahjb** [comment]
Let's take these one at a time:

1.  SOURCE.name and INSTRUMENT.name.  In a rational world, Aaron is right
and this information should
come from a site file or config file.  However, since we don't live in a
rational world, so let us make it really
robust and require that if these are not intentionally provided by the
facility, the former will default to
the string source_name_for_<MODEL>_<SN>_on_<DATE> and the later will
default fo
instument_name_for_<MODEL>_<SN>_on_<DATE> where <MODEL> is the model number
of
the detector, <SN> is the serial number of the detector, and <DATE> is the
date-time string at
which the information was entered.

2.  BEAM.total_flux and ENTRY.end_time_estimated.  Again Aaron is right,
but I don't see a way to
make it more robust other than by leaving them as required and hoping that
this might embarrass a few
facilities into providing the information.

3.  Aaron is right.

**Comment by soph-dec** [comment]
Thank you both for your input and the discussion!

My thoughts:
1. Adding a default seems to make the field "less required", we already discussed that in #1143. Also, (at least in our case) detector model, detector serial and date are already part of the metadata (DETECTOR.description, DETECTOR.serial_number and ENTRY.start_time resp.), so this default would not add any new information. But if the NXmx community feels this default would be useful, it can be added of course. If that is the case, I think this default it should be part of the documentation.
2. That means for the software provided by the manufacturer, all that is required is that the API supports setting those values. It is the responsibility of the faculty or the user to actually set them.

So the only open question for me would be if the default proposed by @yayahjb is desired or not, and also if that default should be applied to SAMPLE.name as well.

**Comment by phyy-nx** [comment]
From NIAC discussion Sep 15 2022.

Regarding 1., we don't think we need to explicitly document that the detector manufacturer can assemble a default from known information such as serial number and model.  Please feel free to do so :)
Regarding 2., that's right.
Regarding SAMPLE.name, if you make it required in the API it will be up to the beamline to supply it, which likely means the user will need to supply something to a beamline interface.

Reasonable?  It's hard to come to perfect concordance here as it's a careful dance between many parties.  If you are satisfied @soph-dec, can you close the issue?  Thanks.

**Comment by soph-dec** [comment]
Thank you for your reply.

We would prefer to refrain from adding defaults, since it basically masks the fact that there is information missing. But we will make those values available via API. We will not force users to give that information though, since we have a lot of different customers and not all of them in the field of macro-molecular crystallography.

So from my side, this issue is resolved and I will close it, thank you all for taking the time to look into this.
